# 자동 생성된 이미지 설정 파일
# 엑셀: image_info.xlsx 기준

IMAGE_RULES = {
    "LC_A_ADV": {
        "material_img": 0,
        "option_img": 3,
        "practical_img": 0,
        "type": "real",
    },
    "LC_A_BA": {
        "material_img": 0,
        "option_img": 4,
        "practical_img": 0,
        "type": "illustrate",
    },
    "LC_A_CO": {
        "material_img": 0,
        "option_img": 3,
        "practical_img": 0,
        "type": "illustrate",
    },
    "LC_A_HJ": {"material_img": 0, "option_img": 3, "practical_img": 0, "type": "real"},
    "LC_A_PS": {
        "material_img": 0,
        "option_img": 3,
        "practical_img": 0,
        "type": "illustrate",
    },
    "LC_A_ST": {
        "material_img": 0,
        "option_img": 3,
        "practical_img": 0,
        "type": "illustrate",
    },
    "LC_B_ADV": {
        "material_img": 0,
        "option_img": 0,
        "practical_img": 0,
        "type": "real",
    },
    "LC_B_CO": {
        "material_img": 0,
        "option_img": 0,
        "practical_img": 0,
        "type": "illustrate",
    },
    "LC_B_HJ": {"material_img": 0, "option_img": 0, "practical_img": 0, "type": "real"},
    "LC_B_PS": {
        "material_img": 0,
        "option_img": 0,
        "practical_img": 0,
        "type": "illustrate",
    },
    "LC_C_BA": {
        "material_img": 0,
        "option_img": 4,
        "practical_img": 0,
        "type": "illustrate",
    },
    "LC_C_PS": {
        "material_img": 0,
        "option_img": 3,
        "practical_img": 0,
        "type": "illustrate",
    },
    "LC_C_ST": {
        "material_img": 0,
        "option_img": 3,
        "practical_img": 0,
        "type": "illustrate",
    },
    "LC_D_BA": {
        "material_img": 0,
        "option_img": 0,
        "practical_img": 0,
        "type": "illustrate",
    },
    "LC_D_JR": {
        "material_img": 0,
        "option_img": 0,
        "practical_img": 0,
        "type": "illustrate",
    },
    "LC_D_ST": {
        "material_img": 0,
        "option_img": 0,
        "practical_img": 0,
        "type": "illustrate",
    },
    "LC_E_ADV": {
        "material_img": 0,
        "option_img": 0,
        "practical_img": 0,
        "type": "real",
    },
    "LC_E_BA": {
        "material_img": 0,
        "option_img": 0,
        "practical_img": 0,
        "type": "illustrate",
    },
    "LC_E_HJ": {"material_img": 0, "option_img": 0, "practical_img": 0, "type": "real"},
    "LC_E_JR": {
        "material_img": 0,
        "option_img": 0,
        "practical_img": 0,
        "type": "illustrate",
    },
    "LC_F_ADV": {
        "material_img": 0,
        "option_img": 0,
        "practical_img": 0,
        "type": "real",
    },
    "LC_F_BA": {
        "material_img": 0,
        "option_img": 0,
        "practical_img": 0,
        "type": "illustrate",
    },
    "LC_F_HJ": {"material_img": 0, "option_img": 0, "practical_img": 0, "type": "real"},
    "LC_F_JR": {
        "material_img": 0,
        "option_img": 0,
        "practical_img": 0,
        "type": "illustrate",
    },
    "LC_G_BA": {
        "material_img": 0,
        "option_img": 0,
        "practical_img": 0,
        "type": "illustrate",
    },
    "LC_G_JR": {
        "material_img": 0,
        "option_img": 0,
        "practical_img": 0,
        "type": "illustrate",
    },
    "RC_A_CO": {
        "material_img": 1,
        "option_img": 0,
        "practical_img": 0,
        "type": "illustrate",
    },
    "RC_A_PS": {
        "material_img": 1,
        "option_img": 0,
        "practical_img": 0,
        "type": "illustrate",
    },
    "RC_B_PS": {
        "material_img": 1,
        "option_img": 0,
        "practical_img": 0,
        "type": "illustrate",
    },
    "RC_C_CO": {
        "material_img": 1,
        "option_img": 0,
        "practical_img": 0,
        "type": "illustrate",
    },
    "RC_C_PS": {
        "material_img": 1,
        "option_img": 0,
        "practical_img": 0,
        "type": "illustrate",
    },
    "RC_D_CO": {
        "material_img": 1,
        "option_img": 0,
        "practical_img": 0,
        "type": "illustrate",
    },
    "RC_D_PS": {
        "material_img": 1,
        "option_img": 0,
        "practical_img": 0,
        "type": "illustrate",
    },
    "RC_E_PS": {
        "material_img": 1,
        "option_img": 0,
        "practical_img": 0,
        "type": "illustrate",
    },
    "RC_F_ADV": {
        "material_img": 0,
        "option_img": 0,
        "practical_img": 0,
        "type": "real",
    },
    "RC_F_BA": {
        "material_img": 0,
        "option_img": 0,
        "practical_img": 0,
        "type": "illustrate",
    },
    "RC_F_HJ": {"material_img": 0, "option_img": 0, "practical_img": 0, "type": "real"},
    "RC_F_JR": {
        "material_img": 0,
        "option_img": 0,
        "practical_img": 0,
        "type": "illustrate",
    },
    "RC_F_ST": {
        "material_img": 0,
        "option_img": 0,
        "practical_img": 0,
        "type": "illustrate",
    },
    "RC_G_ADV": {
        "material_img": 1,
        "option_img": 0,
        "practical_img": 0,
        "type": "real",
    },
    "RC_G_BA": {
        "material_img": 0,
        "option_img": 1,
        "practical_img": 0,
        "type": "illustrate",
    },
    "RC_G_HJ": {"material_img": 1, "option_img": 0, "practical_img": 0, "type": "real"},
    "RC_G_JR": {
        "material_img": 1,
        "option_img": 0,
        "practical_img": 0,
        "type": "illustrate",
    },
    "RC_G_ST": {
        "material_img": 1,
        "option_img": 0,
        "practical_img": 0,
        "type": "illustrate",
    },
    "RC_H_ADV": {
        "material_img": 0,
        "option_img": 0,
        "practical_img": 1,
        "type": "real",
    },
    "RC_H_BA": {
        "material_img": 0,
        "option_img": 0,
        "practical_img": 1,
        "type": "illustrate",
    },
    "RC_H_HJ": {"material_img": 0, "option_img": 0, "practical_img": 1, "type": "real"},
    "RC_H_JR": {
        "material_img": 0,
        "option_img": 0,
        "practical_img": 1,
        "type": "illustrate",
    },
    "RC_H_ST": {
        "material_img": 0,
        "option_img": 0,
        "practical_img": 1,
        "type": "illustrate",
    },
    "RC_I_ADV": {
        "material_img": 0,
        "option_img": 0,
        "practical_img": 0,
        "type": "real",
    },
    "RC_I_BA": {
        "material_img": 0,
        "option_img": 0,
        "practical_img": 0,
        "type": "illustrate",
    },
    "RC_I_HJ": {"material_img": 0, "option_img": 0, "practical_img": 0, "type": "real"},
    "RC_I_JR": {
        "material_img": 0,
        "option_img": 0,
        "practical_img": 0,
        "type": "illustrate",
    },
    "RC_I_ST": {
        "material_img": 0,
        "option_img": 0,
        "practical_img": 0,
        "type": "illustrate",
    },
    "RC_S_HJ": {"material_img": 0, "option_img": 0, "practical_img": 0, "type": "real"},
}
